AUDIT_MODULES = [
    {
        "id": "auth_mfa",
        "category": "Authentication",
        "title": "Multi-Factor Authentication & SSO",
        "innait_module": "2FA | eSSO",
        "innait_module_id": "2fa_esso",
        "priority": "critical",
        "description": "Evaluates strength of authentication mechanisms and single sign-on coverage across enterprise applications.",
        "icon": "shield_check",
        "questions": [
            {"id": "mfa_1", "text": "Do users authenticate to enterprise applications using password only?", "weight": 3, "risk_if_yes": True},
            {"id": "mfa_2", "text": "Is Multi-Factor Authentication (MFA) enforced across all applications?", "weight": 3, "risk_if_yes": False},
            {"id": "mfa_3", "text": "Is MFA enforced for VPN access?", "weight": 2, "risk_if_yes": False},
            {"id": "mfa_4", "text": "Is MFA enforced for Email and collaboration tools?", "weight": 2, "risk_if_yes": False},
            {"id": "mfa_5", "text": "Is MFA enforced for ERP, CRM, and cloud applications?", "weight": 3, "risk_if_yes": False},
            {"id": "mfa_6", "text": "Is biometric authentication used as a second factor?", "weight": 2, "risk_if_yes": False},
            {"id": "mfa_7", "text": "Do users maintain multiple separate credentials for different applications?", "weight": 2, "risk_if_yes": True},
            {"id": "mfa_8", "text": "Is Enterprise Single Sign-On (eSSO) implemented?", "weight": 3, "risk_if_yes": False},
            {"id": "mfa_9", "text": "Does SSO support role-based application access lists?", "weight": 2, "risk_if_yes": False},
            {"id": "mfa_10", "text": "Is maker-checker (transactional biometric) verification in place for approvals?", "weight": 2, "risk_if_yes": False},
            {"id": "mfa_11", "text": "Are authentication events logged and monitored in real time?", "weight": 2, "risk_if_yes": False},
            {"id": "mfa_12", "text": "Are failed authentication attempts alerted and investigated?", "weight": 2, "risk_if_yes": False},
        ],
        "gap_description": "Password-only or fragmented MFA with no enterprise SSO",
        "risk": "Credential theft, phishing, unauthorized access, shadow IT",
        "solution": "Deploy InnaIT 2FA with biometric second factor + eSSO for pass-through authentication to all enterprise applications with role-based access lists.",
        "compliance_refs": ["ISO 27001 A.9.4.2", "NIST SP 800-63B", "PCI-DSS Req 8.3"],
    },
    {
        "id": "windows_ad",
        "category": "Endpoint",
        "title": "Windows Active Directory Login",
        "innait_module": "BioAD",
        "innait_module_id": "bioad",
        "priority": "critical",
        "description": "Assesses security of Windows workstation and Active Directory authentication, including VPN and RDP.",
        "icon": "monitor",
        "questions": [
            {"id": "ad_1", "text": "Do employees log into Windows workstations using password only?", "weight": 3, "risk_if_yes": True},
            {"id": "ad_2", "text": "Is biometric authentication integrated with Active Directory login?", "weight": 3, "risk_if_yes": False},
            {"id": "ad_3", "text": "Are AD credentials reused or shared across systems?", "weight": 3, "risk_if_yes": True},
            {"id": "ad_4", "text": "Are login attempts (success and failure) monitored and alerted?", "weight": 2, "risk_if_yes": False},
            {"id": "ad_5", "text": "Are shared or generic Windows accounts in use?", "weight": 3, "risk_if_yes": True},
            {"id": "ad_6", "text": "Is MFA enforced for Remote Desktop Protocol (RDP) access?", "weight": 2, "risk_if_yes": False},
            {"id": "ad_7", "text": "Is MFA enforced for VPN connections via BioAD?", "weight": 2, "risk_if_yes": False},
            {"id": "ad_8", "text": "Are Windows group policies enforced centrally for security?", "weight": 2, "risk_if_yes": False},
            {"id": "ad_9", "text": "Are privileged AD accounts protected with additional authentication?", "weight": 3, "risk_if_yes": False},
        ],
        "gap_description": "Password-only Windows/AD login with no biometric enforcement",
        "risk": "Lateral movement, pass-the-hash, credential theft, unauthorized access",
        "solution": "Implement InnaIT BioAD for biometric authentication at Active Directory level, covering OS login, VPN, and RDP with centralized policy enforcement.",
        "compliance_refs": ["ISO 27001 A.9.4.2", "CIS Benchmark - Windows", "NIST SP 800-53 IA-2"],
    },
    {
        "id": "winlogin_legacy",
        "category": "Endpoint",
        "title": "Windows Login & Legacy System Access",
        "innait_module": "BioWinLogin",
        "innait_module_id": "biowinlogin",
        "priority": "high",
        "description": "Covers biometric-secured Windows login for non-AD environments and legacy desktop/application scenarios.",
        "icon": "desktop",
        "questions": [
            {"id": "wl_1", "text": "Are there Windows machines not connected to an Active Directory domain?", "weight": 3, "risk_if_yes": True},
            {"id": "wl_2", "text": "Do standalone workstations use password-only local accounts?", "weight": 3, "risk_if_yes": True},
            {"id": "wl_3", "text": "Is biometric authentication used for local Windows login?", "weight": 3, "risk_if_yes": False},
            {"id": "wl_4", "text": "Are legacy application logins secured with biometric authentication?", "weight": 2, "risk_if_yes": False},
            {"id": "wl_5", "text": "Are shared workstations (kiosks, factory floors) individually user-authenticated?", "weight": 3, "risk_if_yes": False},
            {"id": "wl_6", "text": "Is session locking enforced automatically on idle workstations?", "weight": 2, "risk_if_yes": False},
            {"id": "wl_7", "text": "Are local admin accounts monitored and access-controlled?", "weight": 2, "risk_if_yes": False},
        ],
        "gap_description": "Unmanaged local Windows accounts with no biometric enforcement",
        "risk": "Unauthorized physical access, shared credential abuse, ghost accounts",
        "solution": "Deploy InnaIT BioWinLogin for biometric-secured local Windows login on all non-domain and standalone workstations including kiosks.",
        "compliance_refs": ["ISO 27001 A.9.4.2", "CIS Control 4", "NIST 800-53 AC-3"],
    },
    {
        "id": "password_manager",
        "category": "Credential Management",
        "title": "Password & Credential Management",
        "innait_module": "Password Manager",
        "innait_module_id": "pwdmgr",
        "priority": "high",
        "description": "Evaluates how enterprise passwords and credentials are stored, managed, and secured for legacy systems that cannot support biometrics.",
        "icon": "key",
        "questions": [
            {"id": "pm_1", "text": "Do employees reuse the same password across multiple systems?", "weight": 3, "risk_if_yes": True},
            {"id": "pm_2", "text": "Are passwords written down or stored in unsecured notes/spreadsheets?", "weight": 3, "risk_if_yes": True},
            {"id": "pm_3", "text": "Is a centralized enterprise password manager in use?", "weight": 3, "risk_if_yes": False},
            {"id": "pm_4", "text": "Are passwords for legacy systems automatically rotated?", "weight": 2, "risk_if_yes": False},
            {"id": "pm_5", "text": "Are shared service account passwords managed in a vault?", "weight": 3, "risk_if_yes": False},
            {"id": "pm_6", "text": "Is password complexity and expiry policy enforced centrally?", "weight": 2, "risk_if_yes": False},
            {"id": "pm_7", "text": "Are legacy application passwords auto-filled without exposing credentials to the user?", "weight": 2, "risk_if_yes": False},
            {"id": "pm_8", "text": "Is access to the password manager itself protected by biometric or MFA?", "weight": 3, "risk_if_yes": False},
            {"id": "pm_9", "text": "Are password usage and access events audited and logged?", "weight": 2, "risk_if_yes": False},
        ],
        "gap_description": "Unmanaged, reused, or plaintext passwords for legacy applications",
        "risk": "Credential stuffing, password spray attacks, shared credential abuse",
        "solution": "Deploy InnaIT Password Manager for biometric-secured credential vault for all legacy systems, with auto-fill and rotation capabilities.",
        "compliance_refs": ["ISO 27001 A.9.4.3", "NIST SP 800-63B", "CIS Control 5"],
    },
    {
        "id": "server_admin",
        "category": "Infrastructure",
        "title": "Server Administration Security",
        "innait_module": "BioNIX",
        "innait_module_id": "bionix",
        "priority": "critical",
        "description": "Assesses how administrators access Linux/Unix servers and cloud infrastructure, covering SSH, root access, and privileged sessions.",
        "icon": "server",
        "questions": [
            {"id": "srv_1", "text": "Do administrators access Linux servers via SSH password authentication?", "weight": 3, "risk_if_yes": True},
            {"id": "srv_2", "text": "Are SSH keys centrally managed, rotated, and access-controlled?", "weight": 2, "risk_if_yes": False},
            {"id": "srv_3", "text": "Are admin credentials shared among multiple team members?", "weight": 3, "risk_if_yes": True},
            {"id": "srv_4", "text": "Are all administrator activities logged with full session recording?", "weight": 3, "risk_if_yes": False},
            {"id": "srv_5", "text": "Do multiple administrators share a common root account?", "weight": 3, "risk_if_yes": True},
            {"id": "srv_6", "text": "Is biometric authentication required before server access is granted?", "weight": 3, "risk_if_yes": False},
            {"id": "srv_7", "text": "Are privileged access requests subject to approval workflows?", "weight": 2, "risk_if_yes": False},
            {"id": "srv_8", "text": "Are cloud infrastructure consoles (AWS, Azure, GCP) protected with MFA?", "weight": 3, "risk_if_yes": False},
            {"id": "srv_9", "text": "Are server access sessions time-limited and auto-terminated?", "weight": 2, "risk_if_yes": False},
            {"id": "srv_10", "text": "Are privileged access anomalies detected and alerted?", "weight": 2, "risk_if_yes": False},
        ],
        "gap_description": "Shared SSH keys/passwords with no individual accountability for server access",
        "risk": "Insider threats, privilege escalation, unaudited privileged access",
        "solution": "Deploy InnaIT BioNIX for biometric-secured, individually attributed server access with full session logging and approval workflows.",
        "compliance_refs": ["ISO 27001 A.9.2.3", "PCI-DSS Req 8.7", "SOC 2 CC6.1"],
    },
    {
        "id": "data_vault",
        "category": "Data Security",
        "title": "Privileged Data & File Security",
        "innait_module": "Vault",
        "innait_module_id": "vault",
        "priority": "high",
        "description": "Evaluates how sensitive files and confidential data are stored, accessed, and protected across the enterprise.",
        "icon": "lock",
        "questions": [
            {"id": "vault_1", "text": "Are confidential files stored in open or unencrypted shared drives?", "weight": 3, "risk_if_yes": True},
            {"id": "vault_2", "text": "Is access to sensitive files role-based and individually attributed?", "weight": 3, "risk_if_yes": False},
            {"id": "vault_3", "text": "Are sensitive files encrypted at rest using strong encryption?", "weight": 3, "risk_if_yes": False},
            {"id": "vault_4", "text": "Is biometric authentication required to access the file vault?", "weight": 3, "risk_if_yes": False},
            {"id": "vault_5", "text": "Are all file access events logged with user identity and timestamp?", "weight": 2, "risk_if_yes": False},
            {"id": "vault_6", "text": "Are file downloads and exports monitored and controlled?", "weight": 2, "risk_if_yes": False},
            {"id": "vault_7", "text": "Is Data Loss Prevention (DLP) implemented for sensitive data?", "weight": 2, "risk_if_yes": False},
            {"id": "vault_8", "text": "Are backups of sensitive data encrypted and access-controlled?", "weight": 2, "risk_if_yes": False},
            {"id": "vault_9", "text": "Are file access rights reviewed and recertified periodically?", "weight": 2, "risk_if_yes": False},
            {"id": "vault_10", "text": "Are confidential documents protected from printing/screenshotting?", "weight": 1, "risk_if_yes": False},
        ],
        "gap_description": "Unencrypted, open file shares with no biometric access control",
        "risk": "Data leakage, regulatory non-compliance, IP theft",
        "solution": "Deploy InnaIT Vault for biometric-encrypted file storage with granular role-based access, complete audit trail, and DLP enforcement.",
        "compliance_refs": ["ISO 27001 A.8.2.3", "GDPR Art. 32", "PCI-DSS Req 3.4"],
    },
    {
        "id": "attendance",
        "category": "Workforce",
        "title": "Workforce Identity & Attendance",
        "innait_module": "TAS",
        "innait_module_id": "tas",
        "priority": "medium",
        "description": "Evaluates biometric time and attendance, including multi-location, shift management, and payroll integration.",
        "icon": "clock",
        "questions": [
            {"id": "tas_1", "text": "Is employee attendance tracked manually or via swipe/proximity cards?", "weight": 3, "risk_if_yes": True},
            {"id": "tas_2", "text": "Is biometric verification used for attendance capture?", "weight": 3, "risk_if_yes": False},
            {"id": "tas_3", "text": "Are attendance records tamper-proof and audit-trailed?", "weight": 2, "risk_if_yes": False},
            {"id": "tas_4", "text": "Is attendance data integrated in real-time with HRMS/payroll?", "weight": 2, "risk_if_yes": False},
            {"id": "tas_5", "text": "Are multi-location/branch attendance policies enforced centrally?", "weight": 2, "risk_if_yes": False},
            {"id": "tas_6", "text": "Are shift calendars and holiday schedules managed in the system?", "weight": 1, "risk_if_yes": False},
            {"id": "tas_7", "text": "Are contractors and third-party workers included in attendance tracking?", "weight": 2, "risk_if_yes": False},
            {"id": "tas_8", "text": "Is geo-fencing or location-based attendance enforced for remote workers?", "weight": 2, "risk_if_yes": False},
            {"id": "tas_9", "text": "Are overtime and leave requests validated against biometric attendance?", "weight": 1, "risk_if_yes": False},
        ],
        "gap_description": "Manual or card-based attendance with no biometric identity verification",
        "risk": "Buddy punching, attendance fraud, payroll leakage, compliance gaps",
        "solution": "Deploy InnaIT TAS for biometric time-and-attendance with city/branch/shift support, geo-fencing for remote workers, and real-time HRMS integration.",
        "compliance_refs": ["ISO 27001 A.7.1", "Labour Law Compliance", "GDPR Art. 9"],
    },
    {
        "id": "event_verify",
        "category": "Identity Verification",
        "title": "Event & Process Identity Verification",
        "innait_module": "EVS",
        "innait_module_id": "evs",
        "priority": "medium",
        "description": "Assesses identity verification for recruitment, online assessments, events, and multi-stage processes.",
        "icon": "user_check",
        "questions": [
            {"id": "evs_1", "text": "Is participant identity verified biometrically at events or exams?", "weight": 3, "risk_if_yes": False},
            {"id": "evs_2", "text": "Are remote participants authenticated before joining online assessments?", "weight": 3, "risk_if_yes": False},
            {"id": "evs_3", "text": "Is impersonation risk present in recruitment or screening processes?", "weight": 3, "risk_if_yes": True},
            {"id": "evs_4", "text": "Are candidates' identities verified across multiple stages of a process?", "weight": 2, "risk_if_yes": False},
            {"id": "evs_5", "text": "Is biometric verification linked to government-issued ID documents?", "weight": 2, "risk_if_yes": False},
            {"id": "evs_6", "text": "Are verification events timestamped and audit-logged?", "weight": 2, "risk_if_yes": False},
            {"id": "evs_7", "text": "Is liveness detection used to prevent spoofing during verification?", "weight": 2, "risk_if_yes": False},
        ],
        "gap_description": "No structured identity verification for events, exams, or multi-stage processes",
        "risk": "Impersonation, proxy participation, fraudulent assessments",
        "solution": "Deploy InnaIT EVS for biometric identity verification with liveness detection, ID document matching, and full audit trail across events and recruitment.",
        "compliance_refs": ["ISO 27001 A.9.2.1", "eKYC Standards", "GDPR Art. 5"],
    },
    {
        "id": "enterprise_apps",
        "category": "Application Security",
        "title": "Enterprise Application Integration",
        "innait_module": "InnaIT Core SDK",
        "innait_module_id": "core_sdk",
        "priority": "high",
        "description": "Evaluates how enterprise applications (ERP, CRM, bespoke software) are secured and integrated with the biometric identity platform.",
        "icon": "grid",
        "questions": [
            {"id": "app_1", "text": "Do users maintain separate logins for each enterprise application?", "weight": 3, "risk_if_yes": True},
            {"id": "app_2", "text": "Are ERP and CRM systems integrated with a central identity provider?", "weight": 3, "risk_if_yes": False},
            {"id": "app_3", "text": "Is biometric authentication available for bespoke/internal applications?", "weight": 3, "risk_if_yes": False},
            {"id": "app_4", "text": "Do enterprise applications support API-based identity integration (SDK/REST)?", "weight": 2, "risk_if_yes": False},
            {"id": "app_5", "text": "Is application access governed by a central role/entitlement management system?", "weight": 2, "risk_if_yes": False},
            {"id": "app_6", "text": "Are application access rights reviewed periodically and de-provisioned on exit?", "weight": 3, "risk_if_yes": False},
            {"id": "app_7", "text": "Are application access events correlated with identity logs for SIEM?", "weight": 2, "risk_if_yes": False},
        ],
        "gap_description": "Siloed application logins with no central biometric identity integration",
        "risk": "Orphaned accounts, over-privileged access, shadow IT, audit gaps",
        "solution": "Integrate all enterprise applications with InnaIT Core SDK for biometric SSO, centralized provisioning/de-provisioning, and unified access governance.",
        "compliance_refs": ["ISO 27001 A.9.2.2", "SOC 2 CC6.2", "CIS Control 6"],
    },
    {
        "id": "innaitkey",
        "category": "Physical & Logical Security",
        "title": "InnaITKey — Zero-Trust Access Control",
        "innait_module": "InnaITKey (Precision Group)",
        "innait_module_id": "innaitkey",
        "priority": "high",
        "description": "Evaluates convergence of physical and logical access using InnaITKey — a hardware security key from Precision Group that combines biometric, PKI, and FIDO2 for zero-trust environments.",
        "icon": "fingerprint",
        "questions": [
            {"id": "ik_1", "text": "Does physical access control (doors, turnstiles) share identity data with IT systems?", "weight": 3, "risk_if_yes": False},
            {"id": "ik_2", "text": "Are hardware security keys (FIDO2/PIV/PKI) used for privileged access?", "weight": 3, "risk_if_yes": False},
            {"id": "ik_3", "text": "Is biometric identity bound to a physical hardware token for high-security areas?", "weight": 3, "risk_if_yes": False},
            {"id": "ik_4", "text": "Are there high-value systems requiring zero-trust, certificate-based authentication?", "weight": 3, "risk_if_yes": True},
            {"id": "ik_5", "text": "Is certificate lifecycle management (issuance, revocation) centralized?", "weight": 2, "risk_if_yes": False},
            {"id": "ik_6", "text": "Are digital signatures on documents and transactions biometrically bound?", "weight": 2, "risk_if_yes": False},
            {"id": "ik_7", "text": "Is smartcard or hardware token login enforced for sensitive workstations?", "weight": 3, "risk_if_yes": False},
            {"id": "ik_8", "text": "Are access events from physical and logical systems correlated and audited?", "weight": 2, "risk_if_yes": False},
            {"id": "ik_9", "text": "Are tokens/keys inventoried, tamper-detected, and remotely revocable?", "weight": 2, "risk_if_yes": False},
            {"id": "ik_10", "text": "Is FIDO2/WebAuthn enforced for passwordless authentication on critical systems?", "weight": 3, "risk_if_yes": False},
        ],
        "gap_description": "Physical and logical access are siloed with no biometric hardware key enforcement",
        "risk": "Tailgating, stolen token abuse, PKI mismanagement, zero-trust gaps",
        "solution": "Deploy InnaITKey (Precision Group) for converged physical-logical access with biometric-bound FIDO2/PIV hardware keys, certificate management, and digital signature binding.",
        "compliance_refs": ["ISO 27001 A.11.1", "FIDO2 / WebAuthn", "NIST SP 800-116", "PIV Standard"],
    },
    {
        "id": "governance",
        "category": "Governance & Compliance",
        "title": "IAM Governance, Audit & Compliance",
        "innait_module": "InnaIT Platform (All Modules)",
        "innait_module_id": "governance",
        "priority": "high",
        "description": "Evaluates overall IAM governance maturity, including access reviews, policies, audit readiness, and regulatory compliance.",
        "icon": "clipboard",
        "questions": [
            {"id": "gov_1", "text": "Is there a formal, documented IAM policy in place?", "weight": 2, "risk_if_yes": False},
            {"id": "gov_2", "text": "Are user access rights formally reviewed and recertified at least annually?", "weight": 3, "risk_if_yes": False},
            {"id": "gov_3", "text": "Is there a defined Joiner-Mover-Leaver (JML) process with automated de-provisioning?", "weight": 3, "risk_if_yes": False},
            {"id": "gov_4", "text": "Are privileged accounts subject to Privileged Access Management (PAM)?", "weight": 3, "risk_if_yes": False},
            {"id": "gov_5", "text": "Are all access and authentication events retained in a tamper-proof audit log?", "weight": 3, "risk_if_yes": False},
            {"id": "gov_6", "text": "Is there a single unified dashboard for IAM visibility across all systems?", "weight": 2, "risk_if_yes": False},
            {"id": "gov_7", "text": "Are IAM controls mapped to regulatory requirements (GDPR, ISO 27001, PCI-DSS)?", "weight": 2, "risk_if_yes": False},
            {"id": "gov_8", "text": "Is there an incident response plan for identity-related breaches?", "weight": 2, "risk_if_yes": False},
            {"id": "gov_9", "text": "Are third-party and vendor access accounts individually managed and time-limited?", "weight": 2, "risk_if_yes": False},
            {"id": "gov_10", "text": "Are IAM metrics (orphaned accounts, over-privileged users) tracked and reported?", "weight": 2, "risk_if_yes": False},
        ],
        "gap_description": "Ad-hoc IAM governance with no unified audit trail or policy framework",
        "risk": "Regulatory non-compliance, audit failures, undetected access anomalies",
        "solution": "Unify IAM governance across all InnaIT modules with centralized dashboard, automated JML workflows, compliance reporting, and tamper-proof audit logs.",
        "compliance_refs": ["ISO 27001 A.9.2", "SOC 2 CC6", "GDPR Art. 30", "PCI-DSS Req 7-8"],
    },
]

MODULE_INFO = {
    "2fa_esso": {
        "name": "2FA | eSSO",
        "tagline": "Biometric Second Factor + Enterprise Single Sign-On",
        "color": "#3b82f6",
    },
    "bioad": {
        "name": "BioAD",
        "tagline": "Biometric Windows Active Directory Authentication",
        "color": "#8b5cf6",
    },
    "biowinlogin": {
        "name": "BioWinLogin",
        "tagline": "Biometric Local Windows Login for Non-Domain Systems",
        "color": "#6366f1",
    },
    "pwdmgr": {
        "name": "Password Manager",
        "tagline": "Biometric-Secured Enterprise Credential Vault",
        "color": "#f59e0b",
    },
    "bionix": {
        "name": "BioNIX",
        "tagline": "Biometric Linux/Unix Server Admin Access",
        "color": "#ef4444",
    },
    "vault": {
        "name": "Vault",
        "tagline": "Biometric Encrypted File & Data Security",
        "color": "#10b981",
    },
    "tas": {
        "name": "TAS",
        "tagline": "Biometric Time & Attendance System",
        "color": "#14b8a6",
    },
    "evs": {
        "name": "EVS",
        "tagline": "Event & Identity Verification System",
        "color": "#f97316",
    },
    "core_sdk": {
        "name": "InnaIT Core SDK",
        "tagline": "Enterprise Application Biometric Integration",
        "color": "#06b6d4",
    },
    "innaitkey": {
        "name": "InnaITKey",
        "tagline": "Precision Group — Biometric FIDO2/PKI Hardware Key",
        "color": "#a855f7",
    },
    "governance": {
        "name": "InnaIT Platform",
        "tagline": "Unified IAM Governance & Compliance Dashboard",
        "color": "#64748b",
    },
}
